### PR TITLE
Label time since last send/receive in listpeers output

### PR DESCRIPTION
**Pull request by jstasiak**
Took me longer than it should to find out what those values meant, this
label could be useful to others.

### CODE REVIEW

**Comment by laduke** [comment]
Neat. Can you post an example of the output?

**Comment by jstasiak** [comment]
Sure:

```
% ./zerotier-cli listpeers
200 listpeers <ztaddr> <path;time in ms since last send;time in ms since last receive> <latency> <version> <role>
200 listpeers 3610ad5189 - -1 1.2.12 LEAF
200 listpeers 8841408a2e 46.101.160.249/9993;3836;3754 176 1.1.5 PLANET
200 listpeers 9d219039f3 188.166.94.177/9993;3836;14395 307 1.1.5 PLANET
200 listpeers af78bf9436 35.236.10.22/44740;3644;3644 299 1.2.13 LEAF
```

I realise it's a bit on the verbose side but I chose that instead of risking being too terse. I also thought about something like this `<path;time in ms since last send;...receive>` but I'm not sure how I feel about it.

**Comment by laduke** [comment]
Hmm, that would make `zerotier-cli listpeers | column -t` not line up anymore. 

(I have no control over merging here, just think this is interesting)

**Comment by adamierymenko** [comment]
Might tweak a bit and merge. Thanks!

**Pull request closed without merging**
