### PR TITLE
Update client JSON API endpoint address in README.md

### PR DESCRIPTION
**Pull request by joseph-henry**
User pointed out an inconsistency in our documentation: https://github.com/zerotier/ZeroTierOne/issues/2198

### CODE REVIEW

**Comment by joseph-henry** [comment]
Yeah I thought about that as well since "available at" doesn't exclude other addresses but felt it was more straightforward to list what it binds to.

**Comment by glimberg** [comment]
Yeah, but I think this change makes it even more unclear.

**Comment by glimberg** [comment]
Now it reads like you can control the API from anywhere by default as long as you have the key.  That's not the case.

**Comment by glimberg** [comment]
looks good to me

**Pull request merged**
