### PR TITLE
Add Arm64 Support for Windows

### PR DESCRIPTION
**Pull request by chenxijun**
It works well now on my Surface Pro X.

### CODE REVIEW

**Comment by chenxijun** [comment]
Some important information should be declared:
I found some buiding problems in the module `zeroidc`, when using `--target=aarch64-pc-windows-msvc` on my amd64 computer. I spotted that it was caused by an upstream module `ring`, which doesn't work properly at the version `0.16.20`.
Therefore, I try to update it to the [github](https://github.com/briansmith/ring) version of it. The non-relesed 0.17 version works well, but the new one is incompatible with other modules😂. Thus, the only thing I could do was to use the patch feature of cargo, which might, however, cause some unexpectable problems when other modules update. Anyway, it works now😊.

**Comment by conioh** [comment]
I would like it very much to see this get into the product.

**Comment by dmkjr** [comment]
This is interesting.  Any movement on getting it added?

**Comment by hoamle** [comment]
Would love to see this get reviewed and merged as well!

**Comment by conioh** [comment]
Sad.

**Comment by chenxijun** [comment]
> Sad. 

Well, I guess the reason why this pr was closed might be I wrongly chose to merge it into the master branch, which should be dev branch. I can open a new pr, but I'm sorry that I've sold my Surface Pro X, thus making it impossible for me to test whether the code works. So I hope someone who is interested in this work to  pull request.

**Comment by someara** [comment]
Hello!

Sorry about that. I was doing some maintenance for our Github organization, trying to normalize all the branch names, and settings.... this was automatically closed when I deleted the master branch.

Please re-open against dev... I'll work on getting some Windows builds into CI for this.

-s

**Comment by chenxijun** [comment]
> Hello!
> 
> Sorry about that. I was doing some maintenance for our Github organization, trying to normalize all the branch names, and settings.... this was automatically closed when I deleted the master branch.
> 
> Please re-open against dev... I'll work on getting some Windows builds into CI for this.
> 
> -s

Never mind. I've opened a new one. https://github.com/zerotier/ZeroTierOne/pull/1837

**Comment by someara** [comment]
Thanks!

**Pull request closed without merging**
