### PR TITLE
Re-contact peers when default gateway changes

### PR DESCRIPTION
**Pull request by joseph-henry**
This combine's @laduke's default gateway detection code with a new variant of `resetWithinScope` called `resendHelloOnAllPaths` . `Node` now exposes a new function called `resetPeers()` that can be called from the service code. From my initial testing it does correctly detect changes in default gateway and doesn't crash. It likely needs some polishing but hopefully this might help a little.

### CODE REVIEW

**Comment by laduke** [comment]
i rebased on 1.12.1 and force pushed. github seems confused. the version based on dev was borked.

**Comment by joseph-henry** [comment]
I accidentally fat fingered that github review button, didn't mean to mark that as ready to review. Let me know if I need to fix anything on my end.

**Comment by glimberg** [comment]
May have been [04feb30](https://github.com/zerotier/ZeroTierOne/pull/2110/commits/04feb30fbdb3c12538f9b078a09160e585502b94).  Only one with a header change that I see.  Error is:
```
          D:\a\ZeroTierOne\ZeroTierOne\osdep\PortMapper.hpp(14,10): fatal  error C1083: Cannot open include file: 'netinet/in.h': No such file or directory (compiling source file ..\..\osdep\PortMapper.cpp) [D:\a\ZeroTierOne\ZeroTierOne\windows\ZeroTierOne\ZeroTierOne.vcxproj]
         D:\a\ZeroTierOne\ZeroTierOne\osdep\PortMapper.hpp(14,10): fatal  error C1083: Cannot open include file: 'netinet/in.h': No such file or directory (compiling source file ..\..\service\OneService.cpp) [D:\a\ZeroTierOne\ZeroTierOne\windows\ZeroTierOne\ZeroTierOne.vcxproj]
```

**Comment by laduke** [comment]
this is in a commit message somewhre but posting it here as the PR has changed a bunch:

After all the other changes in the service from
debugging this, this seems to not be needed.

It always reconnects for me in about 20 seconds
without resetting the peers/paths

I left the resetter code in the history if we want to try to
get it down to a couple seconds someday. It does work
but you have to poll the default gateway code
quickly and there may be other side effects.

**Pull request merged**
