### PR TITLE
replace _rxQueue list by vector for faster memory access and less all…

### PR DESCRIPTION
**Pull request by mwarning**
…ocations

### CODE REVIEW

**Comment by mwarning** [comment]
_rxQueue does not seem to be used as an ordered container. But some more insight might be required.

**Comment by adamierymenko** [comment]
The typical length of this structure is short, but I was concerned about the use of a vector due to wasted memory. If you suddenly get a ton of packets, it might get kind of long (maybe 10-20 packets) for a little while, then back to zero... but vector won't automatically reclaim.

**Comment by adamierymenko** [comment]
the multi map is kind of unnecessary though... thing thing is the entries are large (full Packet plus fragments buffer)

**Comment by adamierymenko** [comment]
Probably won't merge this one... closing for now. (See our IRC discussion.)

**Pull request closed without merging**
