### PR TITLE
Add forced TCP relay mode

### PR DESCRIPTION
**Pull request by joseph-henry**
This patch implements a `TUNNELED` status indicator and `forceTcpRelay` setting via `local.conf`. For context, see: [1813](https://github.com/zerotier/ZeroTierOne/issues/1813)

Example `zerotier-cli peers` output:

```
200 peers
<ztaddr>   <ver>  <role> <lat> <link>   <lastTX> <lastRX> <path>
9f43ca31c1 1.10.2 LEAF     146 RELAY 94       1368     67.4.57.184/35209
2f41c43bc3 -      PLANET   326 RELAY 8947     3601     51.7.252.248/9993
6fa374adc1 -      PLANET   154 RELAY 8947     3798     143.112.107.66/9993
af92c43dc5 1.10.2 LEAF     176 RELAY 8438     8438     32.218.76.229/30649
cfb37a3dc1 -      PLANET   254 RELAY 8947     3700     81.18.53.154/9993
7f44c43bc7 -      PLANET    89 RELAY 11982    3870     134.124.8.124/9993
NOTE: Currently tunneling through a TCP relay. Ensure that UDP is not blocked.
```

Example `zerotier-cli status` output:

```
200 info 7fab74fdc2 1.10.2 TUNNELED
```

To enable this, use:

```
{
  "settings":
  {
    "tcpFallbackRelay": "5.78.52.214/443",
    "forceTcpRelay":true
  }
}
```

I've set up a relay at `5.78.52.214/443` that can be used for testing. Once we merge this I'll take down the relay.

### CODE REVIEW

**Review by glimberg — COMMENTED** [review]
looks good to me

**Comment by laduke** [comment]
Sweet. It's working for me. 

I'm not getting the `NOTE: Currently tunneling through a TCP relay. Ensure that UDP is not blocked.` message for some reason.

**Comment by joseph-henry** [comment]
It'll only show it for `peers` and not `listpeers` since I didn't want to break what people might be parsing. If that's not the issue I can take a look.

**Comment by laduke** [comment]
That message _is_ working. My bad.

**Comment by joseph-henry** [comment]
I'm going to close this PR since its contents were already merged by another PR (https://github.com/zerotier/ZeroTierOne/pull/1844) that was on another branch originally based on this branch.

**Pull request closed without merging**
