### PR TITLE
tcp-proxy: fix build

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by laduke** [comment]
This PR works on my machine. `dev` doesn't build.

**Comment by laduke** [comment]
I'm not sure... It seems like either:

- add ifdefs to to osdep/Phy.hpp, 
- or compile in the metrics but not be able to get them

i don't want a write the metrics http server right now!

**Comment by laduke** [comment]
I've removed the ifdef.

**Comment by Mic92** [comment]
compiles here.

**Comment by laduke** [comment]
sorry to remove all your commits! thanks!

**Comment by laduke** [comment]
merged in #2065

**Pull request closed without merging**
