### PR TITLE
Default ethertypes

### PR DESCRIPTION
**Pull request by keesbos**
When there are no rules defined, nothing is permitted. In principle a correct implementation, but a zt-net without traffic doesn't make sense. So, I propose to allow IPv4, ARP, and IPv6 ethernet frames when no rules are defined. I think that's kind of the 'standard' use case.

### CODE REVIEW

**Comment by keesbos** [comment]
Should go to dev :-(

**Comment by adamierymenko** [comment]
Hrm... problem is this conflicts with upcoming changes. The etherTypes thing is getting replaced by a full-blown OpenFlow-like rules engine.

**Comment by adamierymenko** [comment]
In a proper rules engine 'do nothing' is and should be the default behavior if you fall off the end of the rules queue. I think if there's a problem here it should be fixed at the UI level -- the UI should create new networks with sane defaults. We *could* make the default settings for a new network in the NetworkController do this.

**Comment by adamierymenko** [comment]
In other words, make this the default rule set if no rules are defined when a new network is created.

**Pull request closed without merging**
