### PR TITLE
Synology Docker: update entrypoint.sh

### PR DESCRIPTION
**Pull request by deekue**
- propagate TERM/QUIT/INT signals
- add some basic logging
- check for unbound variables
- update "route helper"
   - run as subshell, exit if zerotier-one is unavailable so pod can be restarted
   - only call `zerotier-cli` once, avoids race conditions
   - only add default routes if allowDefault is enabled for that network
   - add some more error handling
   - sleep after all networks are processed

### CODE REVIEW

**Comment by joseph-henry** [comment]
Thanks, this looks like really good work. Testing this now. The only problem that I see is:

At the beginning,

```
if ! NETWORK_LIST="$(zerotier-cli -j listnetworks)"
then
  echo "Route helper: $NETWORK_LIST" >&2
  exit 1
fi
```

If ZT takes longer than 15s to start up (low-powered CPU devices could when generating an initial node ID) this script will exit and never be called again. This would result in routes failing to be added. I might lengthen that initial wait interval.

**Comment by erikh** [comment]
poll it

------- Original Message -------

**Comment by deekue** [comment]
switched to polling and made the wait and sleep interval configurable via Docker env vars.  
Defaults are 15s sleep and 90s total wait.

**Comment by joseph-henry** [comment]
I've tested this and verified that it works. Thank you for this excellent work. I'll merge this and push new builds momentarily.

**Pull request merged**
