### PR TITLE
Fix for use of std::unique on std::vector

### PR DESCRIPTION
**Pull request by keesbos**
The std::unique function does update the values in the vector, but does not alter the length (i.e. the return value of .end() )

Example:
With the rules I had ethertypes 0000, 0800, 0000. The config (saved in /var/lib/zerotier/networks.d) had 0000, 0800, 0800. After popping the elements where end != vector.end(), the values became 0000, 0800.

### CODE REVIEW

**Comment by adamierymenko** [comment]
You've got to be kidding me. I'm [astonished](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), therefore this is IMO a bug in STL.

I think I might fix this myself in a cleaner way by creating Utils::vectorUnique(). Sigh.

**Comment by adamierymenko** [comment]
Oh right! It never does! Duh!

It can't. It gets iterators, not the object in question. I'll make a version that does what I want.

**Comment by adamierymenko** [comment]
The way to do this is:

    container.erase(std::unique(container.begin(),container.end()),container.end());

**Comment by keesbos** [comment]
OK. Do you want me to do that, or do-you-do-it-yourself ?

**Comment by adamierymenko** [comment]
Doing it now.

**Comment by keesbos** [comment]
:-)

**Pull request closed without merging**
