### PR TITLE
Add Arm64 Support for Windows

### PR DESCRIPTION
**Pull request by chenxijun**
See also https://github.com/zerotier/ZeroTierOne/pull/1728

Review needed.

### CODE REVIEW

**Review by someara — COMMENTED** [review]
This looks good at a glance... @adamierymenko @glimberg will this explode the driver signing issue?

**Comment by conioh** [comment]
chenxijun noted in the previous issue that they have sold their Surface Pro X and can no longer run the ARM64 build they have prepared.

I currently have access to several Windows ARM64 devices. I don't think I'll have time to work significantly on development but if you'd like me to test ARM64 builds I think I could do that.

**Comment by mcochegrus** [comment]
Hi, I am currently using a VM in Parallels on Mac Silicon, son I can only use Windows 11 ARM, is there a way someone can provide me with an installer for de ARM64 version? 

Thanks in advance.

**Comment by chenxijun** [comment]
> 

Here is an old release: https://github.com/chenxijun/ZeroTierOne/releases
You can merge it into the main branch of this repo and build it yourself!

**Comment by huangyinhaow** [comment]
I noticed that Tailscale started offering Windows on Arm installers a long time ago, ZeroTier has to get with the times and add support for WoA, even without a GUI would be nice, otherwise you will lose some customers. Thanks guys!

**Comment by someara** [comment]
@chenxijun we just merged a pretty big PR un-unvendoring rust to the dev branch.
Can you rebase against that?

update: I'm working on getting windows build infra up for this

**Comment by adamierymenko** [comment]
We're doing this, but this PR is a bit out of date. Merged the other one. Thanks for the help though!

**Comment by hifihedgehog** [comment]
@adamierymenko, just checking in as I work with some Windows on ARM hardware. VPN support is imperative with Snapdragon X Elite and its PC partners on the horizon so let me know what you need tested. I also can work through updating and aligning dependencies so you get a signed release out the door for beta testers who may or may not have next-gen/2024 WOA products in their hands.

**Comment by conioh** [comment]
@hifihedgehog, the MSI that's linked by the text "MSI Installer (x86/x64)" actually has ARM64 drivers and works on my ARM64 machines.

**Pull request closed without merging**
