### PR TITLE
Fix compile on FreeBSD targeting ARMv6 (Raspberry Pi)

### PR DESCRIPTION
**Pull request by darkain**
Attempting to compile ZeroTier on FreeBSD on ARM platforms such as older Raspberry Pi units results in the following error message:

`fails to link: Source object ext/arm32-neon-salsa2012-asm/salsa2012.o has EABI version 0, but target zerotier-one has EABI version 5`

EABI information has been added for the assembler.

Additionally, ARMv6 doesn't support NEON, and it is optional on ARMv7. NEON support is provided by a precompiler directive, so now we check if it exists before including NEON support.

With these changes, ZeroTier compiles and runs perfectly on my Raspberry Pi Zero (using USB NIC)

### CODE REVIEW

**Comment by dch** [comment]
@darkain awesome, that compiles on armv6 but I can't get this to build on armv7 (only available in 12.0-CURRENT, but still)... I've tried sprinkling `-fPIC` and still get issues. Any suggestions for what needs changing?

```
clang++ -O2 -pipe -flax-vector-conversions -fno-strict-aliasing  -O2 -pipe  -flax-vector-conversions -fno-strict-aliasing -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -DZT_NO_TYPE_PUNNING -DZT_USE_ARM32_NEON_ASM_SALSA2012 -DZT_BUILD_PLATFORM=7 -DZT_BUILD_ARCHITECTURE=3 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -fno-rtti -std=c++11  -O2 -pipe  -flax-vector-conversions -fno-strict-aliasing -Wall -fPIE -fvisibility=hidden -fstack-protector -pthread  -DNDEBUG  -DZT_NO_TYPE_PUNNING -DZT_USE_ARM32_NEON_ASM_SALSA2012 -DZT_BUILD_PLATFORM=7 -DZT_BUILD_ARCHITECTURE=3 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -Wall -Werror -g -pthread   -DZT_TRACE -DZT_NO_TYPE_PUNNING -DZT_USE_ARM32_NEON_ASM_SALSA2012 -DZT_BUILD_PLATFORM=7 -DZT_BUILD_ARCHITECTURE=3 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -fno-rtti -std=c++11   -pie -Wl,-z,relro,-z,now  -o zerotier-one node/C25519.o node/Capability.o node/CertificateOfMembership.o node/CertificateOfOwnership.o node/Identity.o node/IncomingPacket.o node/InetAddress.o node/Membership.o node/Multicaster.o node/Network.o node/NetworkConfig.o node/Node.o node/OutboundMulticast.o node/Packet.o node/Path.o node/Peer.o node/Poly1305.o node/Revocation.o node/Salsa20.o node/SelfAwareness.o node/SHA512.o node/Switch.o node/Tag.o node/Topology.o node/Trace.o node/Utils.o ext/arm32-neon-salsa2012-asm/salsa2012.o controller/EmbeddedNetworkController.o controller/DB.o controller/FileDB.o controller/RethinkDB.o osdep/ManagedRoute.o osdep/Http.o osdep/OSUtils.o service/SoftwareUpdater.o service/OneService.o osdep/BSDEthernetTap.o ext/http-parser/http_parser.o one.o 
/usr/bin/ld: error: can't create dynamic relocation R_ARM_ABS32 against local symbol in readonly segment; recompile object files with -fPIC
>>> defined in ext/arm32-neon-salsa2012-asm/salsa2012.o
>>> referenced by ext/arm32-neon-salsa2012-asm/salsa2012.o:(.text+0x630)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [make-bsd.mk:136: one] Error 1
gmake[2]: Leaving directory '/tmp/usr/ports/net/zerotier/work/ZeroTierOne-1.2.12'
gmake[1]: *** [make-bsd.mk:163: debug] Error 2
gmake[1]: Leaving directory '/tmp/usr/ports/net/zerotier/work/ZeroTierOne-1.2.12'
*** Error code 1
```

**Comment by adamierymenko** [comment]
Merged into `dev` since that's where we do work. Merge looks great, but you might want to pull `dev` and test. We don't have an ARM/FreeBSD box handy.

**Comment by darkain** [comment]
@dch I currently only have physical boards for ARMv6, nothing for ARMv7. It might be best currently to entirely omit NEON support from the FreeBSD port for the time being.

Over my free time this weekend, I'll try messing around with QEMU to see if I can get this to build and run on virtual ARM units, but I know those don't perfectly match real-world hardware.

**Comment by darkain** [comment]
WALP, screw it. Amazon Prime free same-day shipping. I'll have a Pi 3B+ tonight to test both ARMv7 and ARMv8 builds on.

**Pull request merged**
